{
 "title": "Gaia monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "environment",
    "query": {
     "query": "label_values(gaia_block_number,job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Block number",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gaia_block_number{job=~\"$env\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Block time delta",
   "type": "timeseries",
   "gridPos": { "h": 18, "w": 19, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "gaia_block_time_delta_seconds{job=~\"$env\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Peers count",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gaia_peers_count{job=~\"$env\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}