---
- name: Build gaiad binary
  delegate_to: 127.0.0.1
  connection: local
  become: false
  block:
    - name: Create tmp dir
      tempfile:
        state: directory
      register: tmp_dir
    - name: Build binary
      shell:
        chdir: "{{ tmp_dir.path }}"
        cmd: "DOCKER_DEFAULT_PLATFORM=linux/amd64 docker run -v $(pwd):/binary golang:1.18-bullseye bash -c 'git clone -b {{ gaia_release_tag }} https://github.com/cosmos/gaia && cd gaia && make install && cp /go/bin/gaiad /binary'"
  when: gaia_build == true

- name: Copy ang initialize gaiad
  block:
    - name: Copy binary to cosmos hosts
      become: true
      copy:
        src: "{{ tmp_dir.path }}/gaiad"
        dest: "{{ gaia_binary_dest_path }}"
        mode: "750"
    - name: Check gaiad initialized
      become: true
      stat:
        path: "/root/.gaia"
      register: gaia_config_path
    - name: Initialize gaiad
      become: true
      shell:
        cmd: "gaiad init {{ gaia_moniker }}"
      when: not gaia_config_path.stat.exists
  when: gaia_build == true

- name: Configure testnet gaiad
  notify: Restart gaiad service
  block:
    - name: Download testnet genesis.json archive
      get_url:
        url: https://github.com/cosmos/testnets/raw/master/public/genesis.json.gz
        dest: /root/.gaia/config
    - name: Extract and replace autogenerated genesis.json
      shell:
        chdir: /root/.gaia/config
        cmd: zcat genesis.json.gz > genesis.json
    - name: Set testnet app.toml options
      template:
        src: app.toml.j2
        dest: /root/.gaia/config/app.toml
    - name: Set testnet config.toml options
      template:
        src: config.toml.j2
        dest: /root/.gaia/config/config.toml
  when: 
    - gaia_reconfigure == true
    - env == "test"

- name: Configure mainnet gaiad
  notify: Restart gaiad service
  block:
    - name: Download mainnet genesis.json archive
      get_url:
        url: https://raw.githubusercontent.com/cosmos/mainnet/master/genesis/genesis.cosmoshub-4.json.gz
        dest: /root/.gaia/config
    - name: Extract and replace autogenerated genesis.json
      shell:
        chdir: /root/.gaia/config
        cmd: zcat genesis.cosmoshub-4.json.gz > genesis.json
    - name: Quicksync address book
      get_url:
        url: https://dl2.quicksync.io/json/addrbook.cosmos.json
        dest: /root/.gaia/config/addrbook.json
    - name: Set mainnet app.toml options
      template:
        src: app.toml.j2
        dest: /root/.gaia/config/app.toml
    - name: Set mainnet config.toml options
      template:
        src: config.toml.j2
        dest: /root/.gaia/config/config.toml
  when: 
    - gaia_reconfigure == true
    - env == "prod"

- name: Ensure gaiad systemd unit file
  notify: Restart gaiad service
  template:
    src: gaiad.service.j2
    dest: /etc/systemd/system/gaiad.service
