---
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 1m
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'gaia-test'
    static_configs:
      - targets:
          - 77.105.141.91:19001

  - job_name: 'gaia-prod'
    static_configs:
      - targets:
          - 43.157.30.2:19001
