---
env: test
if_wan: "ens3"

gaia_build: false
gaia_reconfigure: true

iptables_allow_tcp_ports: ["22"]
iptables_allow_nets_list: []
iptables_allow_nets_ports_list: ["19001"]

# App settings from https://hub.cosmos.network/main/hub-tutorials/join-testnet.html
gaia_min_gas_price: 0.0025uatom
gaia_seeds: "639d50339d7045436c756a042906b9a69970913f@seed-01.theta-testnet.polypore.xyz:26656,3e506472683ceb7ed75c1578d092c79785c27857@seed-02.theta-testnet.polypore.xyz:26656"
gaia_enable_state_sync: true
# current height -1000 from https://www.mintscan.io/cosmos/blocks
gaia_trust_height: 16037429
gaia_trust_hash: "0EFEEC362C3545A3E2299B4CCFB83D6ED616543BCD53B034B2A090D30FA40F20"
gaia_rpc_servers: "http://state-sync-01.theta-testnet.polypore.xyz:26657,http://state-sync-02.theta-testnet.polypore.xyz:26657"
gaia_api_enabled: false
gaia_swagger_enabled: false
gaia_api_listen_addr: "tcp://0.0.0.0:1317"

# Service settings
gaia_limit_nofile: 512
gaia_log_format: "plain"
gaia_log_level: "debug"
