---
env: prod
if_wan: "eth0"

iptables_allow_tcp_ports: ["22"]
iptables_allow_nets_list: []
iptables_allow_nets_ports_list: []

# Base role settings
gaia_build: false
gaia_reconfigure: true

# Build and init options
gaia_release_tag: "v9.1.0"
gaia_binary_dest_path: /usr/local/bin
gaia_moniker: sr-mainnet-node

# App settings from https://hub.cosmos.network/main/hub-tutorials/join-mainnet.html
gaia_min_gas_price: 0.0025uatom
gaia_seeds: ""
gaia_enable_state_sync: true
# current height -1000 from https://www.mintscan.io/cosmos/blocks/
gaia_trust_height: 15378837
gaia_trust_hash: "7AA112412CFCCF13C9897AE0FF694BCCCA6732051D491998F546AFFC2DD3563F"
gaia_rpc_servers: "https://cosmos-rpc.polkachu.com:443,https://rpc-cosmoshub-ia.cosmosia.notional.ventures:443,https://rpc.cosmos.network:443"

# Service settings
gaia_limit_nofile: 4096
gaia_log_format: "json"
gaia_log_level: "error"
