---
env: prod
if_wan: "eth0"

# Firewall settings
# Outside allowed ports:
iptables_allow_tcp_ports: ["22"]
# Trusted networks list:
iptables_allow_nets_list: ["31.172.77.122/32"]
# Ports list for accept connections from allowed networks:
iptables_allow_nets_ports_list: ["19001"]

# Base role settings
gaia_build: false
gaia_reconfigure: true

# Build and init options
# Lambda
gaia_release_tag: "v9.0.0"
gaia_binary_dest_path: /usr/local/bin
gaia_moniker: sr-mainnet-node

# App settings from https://hub.cosmos.network/main/hub-tutorials/join-mainnet.html
gaia_min_gas_price: "0.0025uatom"
# No seeds because of Quicksynk -> addrbook.json
gaia_seeds: ""
gaia_enable_state_sync: "true"
# https://github.com/cosmos/gaia/blob/main/docs/hub-tutorials/join-mainnet.md#state-sync
# current height -1000 from https://www.mintscan.io/cosmos/blocks/
gaia_trust_height: "15414649"
gaia_trust_hash: "EC436159F60C5461AD380B05B8EF05696E971E2808B74D14829A0B99946D1490"
gaia_rpc_servers: "https://cosmos-rpc.polkachu.com:443,https://rpc-cosmoshub-ia.cosmosia.notional.ventures:443,https://rpc.cosmos.network:443"
gaia_trust_period: "168h0m0s"

# Service settings
gaia_limit_nofile: 4096
gaia_log_format: "plain"
gaia_log_level: "error"
